### ISSUE TITLE
DidjImp on linux

### ISSUE THREAD

**Issue by felixgirault** [JesusFreke/didjimp#1]
Hi,

Your project seems great but I couldn't get it to work on Windows, I keep having an issue with parsing the numbers in the measurements file, even with the demo one.

Anyway, I'd rather use it on linux, but I don't know anything about C#.
I saw that it should be feasable (http://didjeridoo.tribe.net/thread/6cd80c41-c179-467e-9fcf-4d66aab248b0), but do you have any tips on making it work with Mono?

**Comment by JesusFreke** [comment]
Hey,

Yeah, I hadn't touched this project in a long time, but I just started
messing with it again recently. I was able to get it to work in linux using
mono, although I don't have any instructions handy. I think I had just
extracted the files from the setup project, and ran the DidjImp.exe
executable with mono.  e.g.

unzip DidjImp.mcs
sudo apt-get install mono-runtime
mono DidjImp.exe

I don't remember if I was able to unzip the .mcs, or if I had to install it
via wine, and then run it from the wine install location. You can also run
the program itself in wine, but I ran into some issues that made it
difficult to use - namely the combo box drop down thingy wouldn't stay
open, it would just immediately close.

I'm actually in the process of rewriting this, although my main target will
be Android, not linux. But the actual calculation logic should be usable in
linux - I can probably make a command line tool or something.

**Comment by felixgirault** [comment]
Thank you, I'll try some of these things and see if it works.

Glad to know that you are working on this again. I thought about porting it to JavaScript, so it could be available in a browser. Maybe if I have some time these days :)

**Comment by JesusFreke** [comment]
Well, I'm rewriting it in kotlin, which I believe can be compiled to javascript, although I haven't looked into that aspect of it, since I'm planning on using it with java.

**Comment by felixgirault** [comment]
I didn't know about Kotlin, but it seems to compile to JavaScript indeed!

I did what you told me with the exe and it works like a charm.
But I keep having this parsing error when loading the example dimensions:

```
Line 0: "0.000 0.01430" - The position 0.0000 is not a valid number.
```

I also tried with `0    0.0143` but the message is then:

```
Line 0: "0.0000 0.01430" - The radius 0.0143 is not a valid number.
```

**Comment by JesusFreke** [comment]
Hmm. I don't remember how the number parsing is done. Maybe try .01430?

**Comment by felixgirault** [comment]
It doesn't work either...
It works fine with integers, but a bore with minimum one meter in diameter is maybe a little too much :D

**Comment by JesusFreke** [comment]
That's strange, something like .0014 is definitely working for me. It might
be a locale issue. Does your locale typically use a comma as a decimal
separator?

**Comment by felixgirault** [comment]
This is it, I'm french and we are using the coma as separator.
Thank you for your time, I'll finally get to play with the app :+1:
